trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: traversemonde
    type: git
    name: traversemonde/traversemonde
    ref: main


steps:
  - checkout: self
      
  # Get template with pathtofile@repositoryname
  - template: update.yml@traversemonde